version: '3.9'

services:
  db:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    networks:
      - db-network

  dbm:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-network


networks:
  db-network:
